module.exports = {
  roles: [
    { id: "red",   name: "Red",   },
    { id: "black", name: "Black", },
  ],
  objects: [
    { prototype: "checkersBoard",      x: 200, y: 200, locked: true},
    { prototype: "checkersPieceRed",   x: 250, y: 200},
    { prototype: "checkersPieceRed",   x: 350, y: 200},
    { prototype: "checkersPieceRed",   x: 450, y: 200},
    { prototype: "checkersPieceRed",   x: 550, y: 200},
    { prototype: "checkersPieceRed",   x: 200, y: 250},
    { prototype: "checkersPieceRed",   x: 300, y: 250},
    { prototype: "checkersPieceRed",   x: 400, y: 250},
    { prototype: "checkersPieceRed",   x: 500, y: 250},
    { prototype: "checkersPieceRed",   x: 250, y: 300},
    { prototype: "checkersPieceRed",   x: 350, y: 300},
    { prototype: "checkersPieceRed",   x: 450, y: 300},
    { prototype: "checkersPieceRed",   x: 550, y: 300},
    { prototype: "checkersPieceBlack", x: 200, y: 550},
    { prototype: "checkersPieceBlack", x: 300, y: 550},
    { prototype: "checkersPieceBlack", x: 400, y: 550},
    { prototype: "checkersPieceBlack", x: 500, y: 550},
    { prototype: "checkersPieceBlack", x: 250, y: 500},
    { prototype: "checkersPieceBlack", x: 350, y: 500},
    { prototype: "checkersPieceBlack", x: 450, y: 500},
    { prototype: "checkersPieceBlack", x: 550, y: 500},
    { prototype: "checkersPieceBlack", x: 200, y: 450},
    { prototype: "checkersPieceBlack", x: 300, y: 450},
    { prototype: "checkersPieceBlack", x: 400, y: 450},
    { prototype: "checkersPieceBlack", x: 500, y: 450},

    { prototype: "d6", x: 650, y: 400},
    { prototype: "d6", x: 675, y: 400},

    { prototype: "redScreen",   x: 100, y: 0,   locked: true},
    { prototype: "blackScreen", x: 100, y: 700, locked: true},
  ],
};
